### PR TITLE
To return files to the status that mostly was done at least twice before

### PR DESCRIPTION
**Pull request by mc12345678**
and has been undone.  Once the appropriate notifiers have been
included in the public version of EP4, all related EP4 files
will be requested to be removed from this as there will be
no further need for them in relation to this plugin to EP4.

### CODE REVIEW

**Comment by mesnitu** [comment]
Yesterday I correct my mistake of uploading my backup files instead of the project. I don't think I'm working with git as I should.  In this commit there are files that need to be merge, others that don't, specially on the export_bookx, because the querys now left joins some names.That's why I try to be updated, so you could see some stuff.  But I'm afraid I don't have much git skills to know how to select what to merge selective.  
If you can, please check my lastest commit and what's in it, so I can easily merge. On this commit I see:  
The easypopulate_4 has a lot of needed changes in the links and forms.
There's a line in the languages. 
The file for ep4 bookx functions , as been updated, and I removed not used functions, so I'm on it.
The module/filelayout is has it should be before I mess up the upload. 
The observer, has some changes. Thinks are going in the same direction, but there are some differences in the global variables. I was using a IMPORT_END and you made a EP4_IMPORT_AFTER_CATEGORY , but that's also in the observer. 

I also try to just to use inside of some observers a :  
 if ($ep_bookx == 1) 
to some stuff, that I think it should only come around, is the bookx fields are enable. 
But, there's probably a better way to wrap all this functions on something like that.

**Comment by mesnitu** [comment]
Ups, my bad again. I see now that that the changes you made on the class is already up to date with the last commit. 
But, still, I don't know how to selective merge files on git.

**Comment by mesnitu** [comment]
Just notice that for the reports table to show in the updateEP4ImportAfterCategory notifier, I have to require the language file ( the new one). But this is looping every time for that file. Possibly it shouldn't

**Comment by mesnitu** [comment]
Possibly a zen extra data file ?

**Comment by mc12345678** [comment]
So... I don't know what git tool you are using on your side. On my end I'd have to figure out what I downloaded a few years ago and have been happy with. I've tried a few and found some more difficult to use than others.

Yes the upload of the incorrect merge did cause some trouble which is why I ended up taking the corrected version. And do all that I did with it. Further, seeing how only some of the previous corrections were incorporated and knowing that there was still some confusion/misunderstanding on multiple things I went with trying to patch the version on git with changes that had been made to the base EP4 files (there were some issues preventing successful operation) as well as the possibility that in correcting the wrong upload that other changes might have been missed.

So yes, there may have been some things that reappeared such as functions that had been deleted from the bookx extra functions file.

As for the definition that was removed from the EP4 file, again this was removed from there and placed in the bookx definitions file. The way the definitions were incorporated in EP4 and the way PHP works this is supported. Definitions work like this: when a constant is defined it can not be "undefined" or reassigned during the current load sequence. To redefine it, the sequence of data must be reloaded. Thus, if you're code is to offer a definition different than the EP4 definition, then it should be loaded within a notifier before EP4 loads the same definition. That has been accomplished here by placing the applicable definition in the bookx version.

In one of the recent posts/discussions it was identified that some data wasn't passing successfully between one portion of the program and another although internal action was successfully completing, I then realized that it was because the necessary variables were not being shared through the use of global variables. So last night before the incorrect upload was performed I had already begun a commit that would populate the observer with the variables used in the included data. Unfortunately between the two uploads things changed again and to be honest, at that point I wanted to show what was needed more than to make sure it was right as I had already devoted quite a bit of time to track down each of the variables. Yes, there may be more shared than used and probably needs to be cleaned up, but there currently there shouldn't be less than necessary so it should still work. The cleanup portion though I somewhat leave for you to do. Again, at least an example is present to just need revision.

So, as to "cherry-picking" changes? That's one reason I was committing very specific changes up to the point that everything went haywire. So, here's a thought and again, not sure how convenient your git tools are. Consider the pull request and what it was pulled against, set a new branch at that point so that it can be returned to it's original state. Then be sure to have committed the changes you have made and I would suggest using yet another new branch, ideally you commit certain things one at a time. Here's where the language was changed, here's where I added a feature, here's where I moved this from here to there, etc... But ultimately you want all of your changes saved, right or wrong that way you can merge in the pull request and then you can start comparing against what you have, what you had, and where you want to go. 

Typically at that point, comments could be made to address something about the code, changes could be made by the original requester and eventually a mutual understanding is met and the code can be simply merged... But by first merging the two, changes away from that merge can be committed with explanation. If you notice my earlier commits I had left information about what was going on. But my last was simply a "one all". Anyways I'm sure I've made things confusing. Sorry.

**Comment by mc12345678** [comment]
So, that was something I was going to comment on at some point. Variables unrelated to a language should not really be assigned in a languages file... It has no bearing on the language really. 

Those variables need to be declared/reset within the sequence of them being used... There are several notifiers in which such could happen. Have to understand when they need to be reset to blank, and where they need to be used. Right now any variable that is to be used within a notifier or in particular in two or more notifiers needs to be globally referenced within each notifier so that its value can be determined and modified within that notifier to become the new value when the notifier is left/done. After modding the code twice, that detail was too much for me to "peacefully" address and ensure it was properly placed...  Glad you noticed it though.

**Comment by mesnitu** [comment]
I use git bash, but I don't use the zen files for the repository, I see now that this opens margin for errors, cause I'll end up copy and pasting from zen to the git folder, and yesterday, I was searching a backup folder for something, and I end up uploading those files. If you didn't made the second commit, I would even notice. 
I like cherry picking, but not on git. I've read some posts about it, but to damn confusing. 
I already downloaded this code and diff it here, and I'm already using it on my local machine ( don't have a dog hunt with a cat , not sure if you have this saying ). 
So, what I can do with my powerful skills, is to release the cat again, and to merge this commit, pull and push with the proper code that I'm working on.
It will be faster for me
The languages... yep, not that good. I started with a default genre in the admin ep4 configuration, but then realize that having all those fields one by one, was not nice. So a language file is something the more or less a zen user has to go through, it seen a simple way of achieving this. 
But now, it's a no no situation. Using this configs on a class it's a no no good situation also. 
They should be configurations. That's why once I've talked about a json file or something like that. 
But, not sure if the result would be the same. But I'll take a look on that. 
Ok, so I'll be merging and trying to put that up2ep4032 up to the changes you've made, plus removing what's not needed anymore.

**Comment by mc12345678** [comment]
So I looked through the code to try to understand the point of the "default" values, but if they are supposed to be "hard coded" they ought to be defined either as added information in the database (easily modifiable from the configuration menu) or as defined constants in some other file that ideally is limited to being loaded by ep4_bookx... There are options, but language files are intended for language related information. As is right now, because those defaults are simple variablesthey can be modified at any time by anything in the program flow.

**Comment by mesnitu** [comment]
ok, I'll be doing that. meanwhile, I'll be commiting this latest's changes.

**Pull request merged**
